name: Build and Deploy Dist

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install

      - name: Generar Prisma Client
        run: npx prisma generate

      - name: Build
        run: npm run build

      - name: Subir dist a rama build
        run: |
          # cambiar a rama build
          git checkout -B build

          # borrar todo menos dist
          find . -mindepth 1 -not -path "./dist*" -delete

          # mover dist al root
          mv dist/* .
          rm -rf dist

          git add .
          git commit -m "Deploy build" || echo "No changes"

          git push origin build --force
